### ISSUE TITLE
Collateral Auction Guardian Bot - Bid calculation

### ISSUE THREAD

**Issue by bette7** [open-web3-stack/guardian#59]
<img width="1165" alt="Screen Shot 2020-08-10 at 5 08 03 PM" src="https://user-images.githubusercontent.com/42193328/89754239-3f4a4800-db2f-11ea-9125-b11d147ce111.png">
This `Last Bid` amount doesn't seem quite right. My margin is 0.1, it should probably multiple the amount of collateral.

This is the transaction [https://acala-testnet.subscan.io/extrinsic/702985-1](https://acala-testnet.subscan.io/extrinsic/702985-1)

**Comment by ermalkaleci** [comment]
That's the price you're bidding not the amount. The formula is very simple 1 - 0.1 x current market price. In other words margin 0.1 is 10% the current market price.

**Comment by ermalkaleci** [comment]
@bette7 I was wrong about it. The bid is the price per amount not the price per unit. I am fixing it.
